FROM alpine:3.7
VOLUME ["/usr/local/etc/nginx"]
COPY nginx.conf /nginx.conf
COPY volconfinit.sh /volconfinit.sh
COPY sleep.sh /sleep.sh
RUN mkdir -p /usr/local/etc/nginx; \
 chmod +x /volconfinit.sh; \
 chmod +x /sleep.sh
ENTRYPOINT ["/volconfinit.sh"]
CMD ["/sleep.sh"]
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s \
        CMD \
        ls /usr/local/etc/nginx/nginx.conf || exit 1
